<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OppoPodsManager.Application</RootNamespace>
    <AssemblyName>OppoPodsManager.Application</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\OppoPodsManager.Core.csproj" />
  </ItemGroup>
</Project>
