<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>OppoPodsManager</AssemblyName>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OppoPodsManager</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <NoWarn>IL2104;IL3053</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <StripSymbols>true</StripSymbols>
    <InvariantGlobalization>false</InvariantGlobalization>
    <DebuggerSupport>false</DebuggerSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.5" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.5" />
    <PackageReference Include="SukiUI" Version="7.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\Localization\Strings*.json" />
    <AvaloniaResource Include="Assets\VisualAssets\**\*" />
    <AvaloniaResource Include="Assets\Oplus\Images\*.png" />
    <EmbeddedResource Include="Assets\Oplus\Data\DeviceModels.json" LogicalName="OppoPodsManager.Assets.Oplus.Data.DeviceModels.json" />
    <EmbeddedResource Include="Assets\Oplus\Data\EqModeNames.json" LogicalName="OppoPodsManager.Assets.Oplus.Data.EqModeNames.json" />
    <EmbeddedResource Include="Assets\Oplus\Data\EqModeNames.en.json" LogicalName="OppoPodsManager.Assets.Oplus.Data.EqModeNames.en.json" WithCulture="false" />
    <EmbeddedResource Include="Assets\Oplus\Data\EqModeNames.de.json" LogicalName="OppoPodsManager.Assets.Oplus.Data.EqModeNames.de.json" WithCulture="false" />
    <EmbeddedResource Include="Assets\Oplus\Data\EqModeNames.ru.json" LogicalName="OppoPodsManager.Assets.Oplus.Data.EqModeNames.ru.json" WithCulture="false" />
    <EmbeddedResource Include="Assets\Localization\Strings.json" LogicalName="OppoPodsManager.Assets.Localization.Strings.json" />
    <EmbeddedResource Include="Assets\Localization\Strings.en.json" LogicalName="OppoPodsManager.Assets.Localization.Strings.en.json" WithCulture="false" />
    <EmbeddedResource Include="Assets\Localization\Strings.de.json" LogicalName="OppoPodsManager.Assets.Localization.Strings.de.json" WithCulture="false" />
    <EmbeddedResource Include="Assets\Localization\Strings.ru.json" LogicalName="OppoPodsManager.Assets.Localization.Strings.ru.json" WithCulture="false" />
  </ItemGroup>
</Project>
